# Generated by Django 3.2 on 2021-04-30 17:53

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_postulante', usuarios.models.NombreField(blank=True, max_length=100, null=True, verbose_name='Nombre del postulante')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_ingresado', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrevista', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Entrevistado/a', 'Entrevistado/a'), ('Evaluado/a', 'Evaluado/a')], default='Pendiente', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
