# Generated by Django 3.2 on 2021-04-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='puesto_trabajo',
        ),
        migrations.AlterField(
            model_name='reunion',
            name='puesto_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.puesto_trabajo'),
        ),
    ]
